#pragma once

#include <keycode.h>

// Maps Windows VK_* codes (0x00-0xFF) to Keycode enum values
static const Keycode vk_to_keycode[256] = {
    /* 0x00 */ Keycode::None,
    /* 0x01 */ Keycode::None, // VK_LBUTTON
    /* 0x02 */ Keycode::None, // VK_RBUTTON
    /* 0x03 */ Keycode::None, // VK_CANCEL
    /* 0x04 */ Keycode::None, // VK_MBUTTON
    /* 0x05 */ Keycode::None, // VK_XBUTTON1
    /* 0x06 */ Keycode::None, // VK_XBUTTON2
    /* 0x07 */ Keycode::None,
    /* 0x08 */ Keycode::Backspace, // VK_BACK
    /* 0x09 */ Keycode::Tab,       // VK_TAB
    /* 0x0A */ Keycode::None,
    /* 0x0B */ Keycode::None,
    /* 0x0C */ Keycode::None,
    /* 0x0D */ Keycode::Enter,     // VK_RETURN
    /* 0x0E */ Keycode::None,
    /* 0x0F */ Keycode::None,
    /* 0x10 */ Keycode::None, // VK_SHIFT (use VK_LSHIFT/VK_RSHIFT)
    /* 0x11 */ Keycode::None, // VK_CONTROL (use VK_LCONTROL/VK_RCONTROL)
    /* 0x12 */ Keycode::None, // VK_MENU (Alt, use VK_LMENU/VK_RMENU)
    /* 0x13 */ Keycode::None,
    /* 0x14 */ Keycode::CapsLock, // VK_CAPITAL
    /* 0x15 */ Keycode::None,
    /* 0x16 */ Keycode::None,
    /* 0x17 */ Keycode::None,
    /* 0x18 */ Keycode::None,
    /* 0x19 */ Keycode::None,
    /* 0x1A */ Keycode::None,
    /* 0x1B */ Keycode::Escape, // VK_ESCAPE
    /* 0x1C */ Keycode::None,
    /* 0x1D */ Keycode::None,
    /* 0x1E */ Keycode::None,
    /* 0x1F */ Keycode::None,
    /* 0x20 */ Keycode::Space, // VK_SPACE
    /* 0x21 */ Keycode::PageUp,   // VK_PRIOR
    /* 0x22 */ Keycode::PageDown, // VK_NEXT
    /* 0x23 */ Keycode::End,      // VK_END
    /* 0x24 */ Keycode::Home,     // VK_HOME
    /* 0x25 */ Keycode::LeftArrow,  // VK_LEFT
    /* 0x26 */ Keycode::UpArrow,    // VK_UP
    /* 0x27 */ Keycode::RightArrow, // VK_RIGHT
    /* 0x28 */ Keycode::DownArrow,  // VK_DOWN
    /* 0x29 */ Keycode::None,
    /* 0x2A */ Keycode::None,
    /* 0x2B */ Keycode::None,
    /* 0x2C */ Keycode::None,
    /* 0x2D */ Keycode::Insert, // VK_INSERT
    /* 0x2E */ Keycode::Delete, // VK_DELETE
    /* 0x2F */ Keycode::None,
    /* 0x30 */ Keycode::Num0,
    /* 0x31 */ Keycode::Num1,
    /* 0x32 */ Keycode::Num2,
    /* 0x33 */ Keycode::Num3,
    /* 0x34 */ Keycode::Num4,
    /* 0x35 */ Keycode::Num5,
    /* 0x36 */ Keycode::Num6,
    /* 0x37 */ Keycode::Num7,
    /* 0x38 */ Keycode::Num8,
    /* 0x39 */ Keycode::Num9,
    /* 0x3A */ Keycode::None,
    /* 0x3B */ Keycode::None,
    /* 0x3C */ Keycode::None,
    /* 0x3D */ Keycode::None,
    /* 0x3E */ Keycode::None,
    /* 0x3F */ Keycode::None,
    /* 0x40 */ Keycode::None,
    /* 0x41 */ Keycode::A,
    /* 0x42 */ Keycode::B,
    /* 0x43 */ Keycode::C,
    /* 0x44 */ Keycode::D,
    /* 0x45 */ Keycode::E,
    /* 0x46 */ Keycode::F,
    /* 0x47 */ Keycode::G,
    /* 0x48 */ Keycode::H,
    /* 0x49 */ Keycode::I,
    /* 0x4A */ Keycode::J,
    /* 0x4B */ Keycode::K,
    /* 0x4C */ Keycode::L,
    /* 0x4D */ Keycode::M,
    /* 0x4E */ Keycode::N,
    /* 0x4F */ Keycode::O,
    /* 0x50 */ Keycode::P,
    /* 0x51 */ Keycode::Q,
    /* 0x52 */ Keycode::R,
    /* 0x53 */ Keycode::S,
    /* 0x54 */ Keycode::T,
    /* 0x55 */ Keycode::U,
    /* 0x56 */ Keycode::V,
    /* 0x57 */ Keycode::W,
    /* 0x58 */ Keycode::X,
    /* 0x59 */ Keycode::Y,
    /* 0x5A */ Keycode::Z,
    /* 0x5B */ Keycode::LeftGUI,   // VK_LWIN
    /* 0x5C */ Keycode::RightGUI,  // VK_RWIN
    /* 0x5D */ Keycode::Application, // VK_APPS
    /* 0x5E */ Keycode::None,
    /* 0x5F */ Keycode::None,
    /* 0x60 */ Keycode::Keypad0,
    /* 0x61 */ Keycode::Keypad1,
    /* 0x62 */ Keycode::Keypad2,
    /* 0x63 */ Keycode::Keypad3,
    /* 0x64 */ Keycode::Keypad4,
    /* 0x65 */ Keycode::Keypad5,
    /* 0x66 */ Keycode::Keypad6,
    /* 0x67 */ Keycode::Keypad7,
    /* 0x68 */ Keycode::Keypad8,
    /* 0x69 */ Keycode::Keypad9,
    /* 0x6A */ Keycode::KeypadAsterisk, // VK_MULTIPLY
    /* 0x6B */ Keycode::KeypadPlus,     // VK_ADD
    /* 0x6C */ Keycode::None,
    /* 0x6D */ Keycode::KeypadMinus,    // VK_SUBTRACT
    /* 0x6E */ Keycode::KeypadPeriod,   // VK_DECIMAL
    /* 0x6F */ Keycode::KeypadSlash,    // VK_DIVIDE
    /* 0x70 */ Keycode::F1,
    /* 0x71 */ Keycode::F2,
    /* 0x72 */ Keycode::F3,
    /* 0x73 */ Keycode::F4,
    /* 0x74 */ Keycode::F5,
    /* 0x75 */ Keycode::F6,
    /* 0x76 */ Keycode::F7,
    /* 0x77 */ Keycode::F8,
    /* 0x78 */ Keycode::F9,
    /* 0x79 */ Keycode::F10,
    /* 0x7A */ Keycode::F11,
    /* 0x7B */ Keycode::F12,
    /* 0x7C */ Keycode::F13,
    /* 0x7D */ Keycode::F14,
    /* 0x7E */ Keycode::F15,
    /* 0x7F */ Keycode::F16,
    /* 0x80 */ Keycode::F17,
    /* 0x81 */ Keycode::F18,
    /* 0x82 */ Keycode::F19,
    /* 0x83 */ Keycode::F20,
    /* 0x84 */ Keycode::F21,
    /* 0x85 */ Keycode::F22,
    /* 0x86 */ Keycode::F23,
    /* 0x87 */ Keycode::F24,
    /* 0x88 */ Keycode::None,
    /* 0x89 */ Keycode::None,
    /* 0x8A */ Keycode::None,
    /* 0x8B */ Keycode::None,
    /* 0x8C */ Keycode::None,
    /* 0x8D */ Keycode::None,
    /* 0x8E */ Keycode::None,
    /* 0x8F */ Keycode::None,
    /* 0x90 */ Keycode::NumLock,     // VK_NUMLOCK
    /* 0x91 */ Keycode::ScrollLock,  // VK_SCROLL
    /* 0x92 */ Keycode::None,
    /* 0x93 */ Keycode::None,
    /* 0x94 */ Keycode::None,
    /* 0x95 */ Keycode::None,
    /* 0x96 */ Keycode::None,
    /* 0x97 */ Keycode::None,
    /* 0x98 */ Keycode::None,
    /* 0x99 */ Keycode::None,
    /* 0x9A */ Keycode::None,
    /* 0x9B */ Keycode::None,
    /* 0x9C */ Keycode::None,
    /* 0x9D */ Keycode::None,
    /* 0x9E */ Keycode::None,
    /* 0x9F */ Keycode::None,
    /* 0xA0 */ Keycode::LeftShift,   // VK_LSHIFT
    /* 0xA1 */ Keycode::RightShift,  // VK_RSHIFT
    /* 0xA2 */ Keycode::LeftControl, // VK_LCONTROL
    /* 0xA3 */ Keycode::RightControl,// VK_RCONTROL
    /* 0xA4 */ Keycode::LeftAlt,     // VK_LMENU
    /* 0xA5 */ Keycode::RightAlt,    // VK_RMENU
    /* 0xA6 */ Keycode::None,
    /* 0xA7 */ Keycode::None,
    /* 0xA8 */ Keycode::None,
    /* 0xA9 */ Keycode::None,
    /* 0xAA */ Keycode::None,
    /* 0xAB */ Keycode::None,
    /* 0xAC */ Keycode::None,
    /* 0xAD */ Keycode::None,
    /* 0xAE */ Keycode::None,
    /* 0xAF */ Keycode::None,
    /* 0xB0 */ Keycode::None,
    /* 0xB1 */ Keycode::None,
    /* 0xB2 */ Keycode::None,
    /* 0xB3 */ Keycode::None,
    /* 0xB4 */ Keycode::None,
    /* 0xB5 */ Keycode::None,
    /* 0xB6 */ Keycode::None,
    /* 0xB7 */ Keycode::None,
    /* 0xB8 */ Keycode::None,
    /* 0xB9 */ Keycode::None,
    /* 0xBA */ Keycode::None,
    /* 0xBB */ Keycode::None,
    /* 0xBC */ Keycode::None,
    /* 0xBD */ Keycode::None,
    /* 0xBE */ Keycode::None,
    /* 0xBF */ Keycode::None,
    /* 0xC0 */ Keycode::None,
    /* 0xC1 */ Keycode::None,
    /* 0xC2 */ Keycode::None,
    /* 0xC3 */ Keycode::None,
    /* 0xC4 */ Keycode::None,
    /* 0xC5 */ Keycode::None,
    /* 0xC6 */ Keycode::None,
    /* 0xC7 */ Keycode::None,
    /* 0xC8 */ Keycode::None,
    /* 0xC9 */ Keycode::None,
    /* 0xCA */ Keycode::None,
    /* 0xCB */ Keycode::None,
    /* 0xCC */ Keycode::None,
    /* 0xCD */ Keycode::None,
    /* 0xCE */ Keycode::None,
    /* 0xCF */ Keycode::None,
    /* 0xD0 */ Keycode::None,
    /* 0xD1 */ Keycode::None,
    /* 0xD2 */ Keycode::None,
    /* 0xD3 */ Keycode::None,
    /* 0xD4 */ Keycode::None,
    /* 0xD5 */ Keycode::None,
    /* 0xD6 */ Keycode::None,
    /* 0xD7 */ Keycode::None,
    /* 0xD8 */ Keycode::None,
    /* 0xD9 */ Keycode::None,
    /* 0xDA */ Keycode::None,
    /* 0xDB */ Keycode::None,
    /* 0xDC */ Keycode::None,
    /* 0xDD */ Keycode::None,
    /* 0xDE */ Keycode::None,
    /* 0xDF */ Keycode::None,
    /* 0xE0 */ Keycode::None,
    /* 0xE1 */ Keycode::None,
    /* 0xE2 */ Keycode::None,
    /* 0xE3 */ Keycode::None,
    /* 0xE4 */ Keycode::None,
    /* 0xE5 */ Keycode::None,
    /* 0xE6 */ Keycode::None,
    /* 0xE7 */ Keycode::None,
    /* 0xE8 */ Keycode::None,
    /* 0xE9 */ Keycode::None,
    /* 0xEA */ Keycode::None,
    /* 0xEB */ Keycode::None,
    /* 0xEC */ Keycode::None,
    /* 0xED */ Keycode::None,
    /* 0xEE */ Keycode::None,
    /* 0xEF */ Keycode::None,
    /* 0xF0 */ Keycode::None,
    /* 0xF1 */ Keycode::None,
    /* 0xF2 */ Keycode::None,
    /* 0xF3 */ Keycode::None,
    /* 0xF4 */ Keycode::None,
    /* 0xF5 */ Keycode::None,
    /* 0xF6 */ Keycode::None,
    /* 0xF7 */ Keycode::None,
    /* 0xF8 */ Keycode::None,
    /* 0xF9 */ Keycode::None,
    /* 0xFA */ Keycode::None,
    /* 0xFB */ Keycode::None,
    /* 0xFC */ Keycode::None,
    /* 0xFD */ Keycode::None,
    /* 0xFE */ Keycode::None,
    /* 0xFF */ Keycode::None
};
