name: build-linux
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-14
      CXX: g++-14
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install GCC 14
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install gcc-14 g++-14

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install autoconf autoconf-archive automake libtool

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
      
      - name: Build
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/recorder/CMakeLists.txt'
          configurePreset: 'vcpkg - Ninja'
          buildPreset: 'CI - Release'

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: recorder-app
          path: '${{ github.workspace }}/recorder/build/recorder-app'
